sudo: false
language: node_js
node_js:
  - "node"
cache: 
  yarn: true
notifications:
  email:
    on_success: never 
    on_failure: never 

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: web/dist/
  on:
    branch: master